return function()
    vim.api.nvim_create_user_command('W', 'write', {})
    vim.api.nvim_create_user_command('Wq', 'wq', {})
    vim.api.nvim_create_user_command('Q', 'quit', {})
    vim.api.nvim_create_user_command('Qa', 'qall', {})
    vim.api.nvim_create_user_command('Wqa', 'wqall', {})
    vim.api.nvim_create_user_command('FO', 'Fo', {})
    vim.api.nvim_create_user_command('Ranker', function (opts)
        require('handdara.util.ranker').ranker(opts.line1, opts.line2)
    end , { range = true })
    vim.api.nvim_create_user_command('StacheOpenTask', function ()
        require'handdara.util.stache'.open_item()
    end, {})
    vim.api.nvim_create_user_command('StacheOpenTask', function ()
        require'handdara.util.stache'.open_item()
    end, {})
    vim.api.nvim_create_user_command('StacheRunAll', function(_) require'handdara.util.stache'.buf_exec_all_blocks(0) end, {})
end
