return function()
    vim.api.nvim_create_user_command('W', 'write', {})
    vim.api.nvim_create_user_command('Wq', 'wq', {})
    vim.api.nvim_create_user_command('Q', 'quit', {})
    vim.api.nvim_create_user_command('Qa', 'qall', {})
    vim.api.nvim_create_user_command('Wqa', 'wqall', {})
    vim.api.nvim_create_user_command('FO', 'Fo', {})
    vim.api.nvim_create_user_command('Ranker', function (opts)
        require('handdara.util.ranker').ranker(opts.line1, opts.line2)
    end , { range = true })
end
