set-option -g mode-keys vi
set-option -g default-shell /bin/bash
#set-option -g status-style bg=magenta,fg=white
#set-option -g status-style bg=black,fg=cyan
set-option -g status-style bg=red,fg=white
set-option -g status-right '%y%M%dT%H%MZ'
set-option -g status-position top
set-option -g status-justify centre
bind 'C-x' source-file ~/.tmux.conf
