set fallback

# quick rebuilding aliases
alias n := switch-nixos
alias h := switch-home-mngr

# just list justs
default: 
    @just -l

build-vm:
    nixos-rebuild build-vm --flake .

update-nvim: 
    nix flake update nix-vimrc

# rebuild NixOS system (flake-based)
switch-nixos:
    sudo nixos-rebuild switch --flake .

# rebuild and switch home-manager (flake-based)
switch-home-mngr: 
    home-manager switch --flake .

# build home-manager (flake-based)
build-home-mngr: 
    home-manager build --flake .

temp-home-mngr: build-home-mngr
    ./result/activate

# test NixOS system rebuild
test-nixos:
    sudo nixos-rebuild test --flake .

# test home-manager rebuild
test-home-mngr: && build-home-mngr
    home-manager -n switch --flake .

# test system & home-manager rebuild
test: test-nixos test-home-mngr 
