let
    colordata = {
        bg = "000b01"; #000b01
        fg = "f9ffde"; #f9ffde
        black = "001501"; #001501
        red = "671b06"; #671b06
        green = "1f4f00"; #1f4f00
        yellow = "4f4a17"; #4f4a17
        blue = "03041c"; #03041c
        magenta = "56564d"; #56564d
        cyan = "066b6b"; #066b6b
        white = "aeb58b"; #aeb58b
        bright_black = "072d09"; #072d09
        bright_red = "ba334b"; #ba334b
        bright_green = "68914d"; #68914d
        bright_yellow = "bcca39"; #bcca39
        bright_blue = "0a3874"; #0a3874
        bright_magenta = "a3a054"; #a3a054
        bright_cyan = "669292"; #669292
        bright_white = "c3f2d0"; #c3f2d0
        theme_name = "sagekit";
        theme_author = "menriss";
    };
in
    with colordata; {
        dark = rec {
            name = "${theme_name}_dark";
            author = "${theme_author}";
            is_light = false;
            base16 = {
                bg = "${bg}";
                fg = "${fg}";
                black = "${black}";
                red = "${red}";
                green = "${green}";
                yellow = "${yellow}";
                blue = "${blue}";
                magenta = "${magenta}";
                cyan = "${cyan}";
                white = "${white}";
                bright_black = "${bright_black}";
                bright_red = "${bright_red}";
                bright_green = "${bright_green}";
                bright_yellow = "${bright_yellow}";
                bright_blue = "${bright_blue}";
                bright_magenta = "${bright_magenta}";
                bright_cyan = "${bright_cyan}";
                bright_white = "${bright_white}";
                base00 = "${base16.bg}";
                base01 = "${base16.bright_blue}";
                base02 = "${base16.bright_green}";
                base03 = "${base16.yellow}";
                base04 = "${base16.green}";
                base05 = "${base16.fg}";
                base06 = "${base16.bright_cyan}";
                base07 = "${base16.bright_white}";
                base08 = "${base16.cyan}"; # incomplete
                base09 = "${base16.magenta}";
                base0A = "${base16.bright_white}";
                base0B = "${base16.bright_yellow}";
                base0C = "${base16.white}";
                base0D = "${base16.bright_magenta}";
                base0E = "${base16.bright_red}";
                base0F = "${base16.red}";
            };
            hexcodes = {
                bg = "#" + base16.bg;
                fg = "#" + base16.fg;
                black = "#" + base16.black;
                red = "#" + base16.red;
                green = "#" + base16.green;
                yellow = "#" + base16.yellow;
                blue = "#" + base16.blue;
                magenta = "#" + base16.magenta;
                cyan = "#" + base16.cyan;
                white = "#" + base16.white;
                bright_black = "#" + base16.bright_black;
                bright_red = "#" + base16.bright_red;
                bright_green = "#" + base16.bright_green;
                bright_yellow = "#" + base16.bright_yellow;
                bright_blue = "#" + base16.bright_blue;
                bright_magenta = "#" + base16.bright_magenta;
                bright_cyan = "#" + base16.bright_cyan;
                bright_white = "#" + base16.bright_white;
                window_focus = hexcodes.green;
            };
            starship = {
                fg1 = hexcodes.yellow; # os
                bg1 = hexcodes.bright_black;
                fg2 = hexcodes.bright_black; # directory
                bg2 = hexcodes.bright_green;
                fg3 = hexcodes.bright_black; # git
                bg3 = hexcodes.magenta;
                fg4 = hexcodes.white; # lang/env
                bg4 = hexcodes.bright_blue;
                fg5 = hexcodes.magenta; # time
                bg5 = hexcodes.blue;
                bgchar = hexcodes.black;
            };
        };
        light = rec {
            name = "${theme_name}_light";
            author = "${theme_author}";
            is_light = true;
            base16 = {
                bg = fg;
                fg = bg;
                black = black;
                red = red;
                green = green;
                yellow = yellow;
                blue = blue;
                magenta = magenta;
                cyan = cyan;
                white = white;
                bright_black = bright_black;
                bright_red = bright_red;
                bright_green = bright_green;
                bright_yellow = bright_yellow;
                bright_blue = bright_blue;
                bright_magenta = bright_magenta;
                bright_cyan = bright_cyan;
                bright_white = bright_white;
                base00 = base16.bg;
                base01 = base16.blue;
                base02 = base16.bright_green;
                base03 = base16.yellow;
                base04 = base16.green;
                base05 = base16.fg;
                base06 = base16.bright_cyan;
                base07 = base16.bright_white;
                base08 = base16.cyan; # incomplete
                base09 = base16.magenta;
                base0A = base16.bright_white;
                base0B = base16.bright_yellow;
                base0C = base16.white;
                base0D = base16.bright_magenta;
                base0E = base16.bright_red;
                base0F = base16.red;
            };
            hexcodes = {
                bg = "#" + base16.bg;
                fg = "#" + base16.fg;
                black = "#" + base16.black;
                red = "#" + base16.red;
                green = "#" + base16.green;
                yellow = "#" + base16.yellow;
                blue = "#" + base16.blue;
                magenta = "#" + base16.magenta;
                cyan = "#" + base16.cyan;
                white = "#" + base16.white;
                bright_black = "#" + base16.bright_black;
                bright_red = "#" + base16.bright_red;
                bright_green = "#" + base16.bright_green;
                bright_yellow = "#" + base16.bright_yellow;
                bright_blue = "#" + base16.bright_blue;
                bright_magenta = "#" + base16.bright_magenta;
                bright_cyan = "#" + base16.bright_cyan;
                bright_white = "#" + base16.bright_white;
                window_focus = hexcodes.bright_red;
            };
            starship = {
                fg1 = hexcodes.yellow; # os
                bg1 = hexcodes.bright_green;
                fg2 = hexcodes.magenta; # directory
                bg2 = hexcodes.bright_magenta;
                fg3 = hexcodes.bright_blue; # git
                bg3 = hexcodes.white;
                fg4 = hexcodes.black; # lang/env
                bg4 = hexcodes.bright_yellow;
                fg5 = hexcodes.white; # time
                bg5 = hexcodes.bright_blue;
                bgchar = hexcodes.magenta;
            };
            ghostty = {
                bg = "ddffc7";
            };
        };
    }
