format = """
[░▒▓](cyan)\
[  ](bg:cyan fg:black)\
[](bg:green fg:cyan)\
$directory\
[](fg:green bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:black)\
$rust\
$c\
$golang\
$haskell\
$conda\
${custom.latex}\
[](fg:black bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$cmd_duration\
\n$character"""

[directory]
style = "fg:black bg:green"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $branch ](fg:black bg:blue)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:black bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[c]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[haskell]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[custom.latex]
symbol = "LaTeX 󰎞 "
detect_extensions = ["tex", "bibtex", "bib"]
style = "bg:black"
format = '[[ $symbol ](fg:blue bg:black)]($style)'

[golang]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[conda]
style = "bg:black"
format = "[[ $symbol ($environment) ](fg:blue bg:black)]($style)"
ignore_base = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:green bg:#1d2230)]($style)'

[cmd_duration]
show_milliseconds = false
disabled = false
style = "italic #394260"
format = "[$duration]($style)"

