alias purge := unlink

starship_toml := 'starship.toml'
starship_to := env_var('HOME') / '.config' / starship_toml
starship_fr := justfile_directory() / starship_toml

# list cmds
default: 
    @just --list

# clean starship configuration toml
unlink:
    rm {{starship_to}}

# symlink starship configuration toml
link:
    ln -svf {{starship_fr}} {{starship_to}}

