ln_file := 'ln -svf'

starship_toml := 'starship.toml'
starship_to := env_var('HOME') / '.config' / starship_toml
starship_fr := justfile_directory() / starship_toml

# list cmds
default: 
    @just --list

# clean starship configuration toml
clean-starship:
    rm -f {{starship_to}}

# symlink starship configuration toml
link-starship:
    {{ln_file}} {{starship_fr}} {{starship_to}}
