[[language]]
name = "latex"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language-server.texlab.config.texlab.symbols]
ignoredPatterns = [ "/Equation/" ]

[language-server.texlab.config.texlab.forwardSearch]
# executable = "zathura" 
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]
executable = "okular"
args = ["--unique", "file:%p#src:%l%f"]

# [language-server.texlab.config.texlab.chktex]
# onEdit = true

[[language]]
name = "haskell"

[language-server.haskell-language-server-wrapper]
command = "haskell-language-server-wrapper"

# [language-server.haskell-language-server-wrapper.config.haskell.plugin.eval]
# exception = true
# globalOn = true

# [language-server.haskell-language-server-wrapper.config.plugin.gadt]
# globalOn = false

[[language]]
name = "matlab"
indent = { tab-width = 2, unit = "  "}

[[language]]
name = "rust"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launc"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true
