ln_dir := 'ln -sv'
rm_tree := 'rm -Rf'

fish_config_ln := env_var('HOME') / '.config' / 'fish'
fish_main_dir := justfile_directory() / 'fish-main'
fish_func_dir := fish_main_dir / 'functions'
fish_cfg_file := fish_config_ln / 'config.fish'

# lists available commands
default:
    @just --list

# symlink main fish configuration
link: purge
    {{ln_dir}} {{fish_main_dir}} {{fish_config_ln}}

# copy fish functions for use, skips collisions
cp-fish-funcs:
    cp -vrn {{fish_func_dir}} {{fish_config_ln}}/functions

# unlinks the fish config dir symlink
unlink:
    rm {{fish_config_ln}}

# purge the fish config dir
purge:
    {{rm_tree}} {{fish_config_ln}}
