let
  colordata = {
    bg = "1b1e1b";
    fg = "8f8f8f";
    black = "1b1e1b";
    red = "fd225c";
    green = "c84678";
    yellow = "e6447f";
    blue = "717374";
    magenta = "747174";
    cyan = "625f62";
    white = "c6bfc2";
    bright_black = "505450";
    bright_red = "fe6ca9";
    bright_green = "ff7db1";
    bright_yellow = "ff8eb7";
    bright_blue = "919591";
    bright_magenta = "9a9d9c";
    bright_cyan = "a3a6a5";
    bright_white = "dbd6d6";
    theme_name = "pink-batman";
    theme_author = "handdara";
  };
in
with colordata; {
  dark = rec {
    name = "${theme_name}_dark";
    author = "${theme_author}";
    is_light = false;
    base16 = {
      bg = "${bg}";
      fg = "${fg}";
      black = "${black}";
      red = "${red}";
      green = "${green}";
      yellow = "${yellow}";
      blue = "${blue}";
      magenta = "${magenta}";
      cyan = "${cyan}";
      white = "${white}";
      bright_black = "${bright_black}";
      bright_red = "${bright_red}";
      bright_green = "${bright_green}";
      bright_yellow = "${bright_yellow}";
      bright_blue = "${bright_blue}";
      bright_magenta = "${bright_magenta}";
      bright_cyan = "${bright_cyan}";
      bright_white = "${bright_white}";
      base00 = "${base16.bg}";
      base01 = "${base16.bright_blue}";
      base02 = "${base16.bright_green}";
      base03 = "${base16.yellow}";
      base04 = "${base16.green}";
      base05 = "${base16.fg}";
      base06 = "${base16.bright_cyan}";
      base07 = "${base16.bright_white}";
      base08 = "${base16.cyan}"; # incomplete
      base09 = "${base16.magenta}";
      base0A = "${base16.bright_white}";
      base0B = "${base16.bright_yellow}";
      base0C = "${base16.white}";
      base0D = "${base16.bright_magenta}";
      base0E = "${base16.bright_red}";
      base0F = "${base16.red}";
    };
    hexcodes = {
      bg = "#" + base16.bg;
      fg = "#" + base16.fg;
      black = "#" + base16.black;
      red = "#" + base16.red;
      green = "#" + base16.green;
      yellow = "#" + base16.yellow;
      blue = "#" + base16.blue;
      magenta = "#" + base16.magenta;
      cyan = "#" + base16.cyan;
      white = "#" + base16.white;
      bright_black = "#" + base16.bright_black;
      bright_red = "#" + base16.bright_red;
      bright_green = "#" + base16.bright_green;
      bright_yellow = "#" + base16.bright_yellow;
      bright_blue = "#" + base16.bright_blue;
      bright_magenta = "#" + base16.bright_magenta;
      bright_cyan = "#" + base16.bright_cyan;
      bright_white = "#" + base16.bright_white;
    };
    wm = {
      window_border = {
        focus = hexcodes.bright_blue;
        normal = hexcodes.black;
        marked = hexcodes.bright_green;
      };
    };
    starship = {
      fg1 = hexcodes.yellow; # os
      bg1 = hexcodes.bright_black;
      fg2 = hexcodes.bright_black; # directory
      bg2 = hexcodes.bright_green;
      fg3 = hexcodes.bright_cyan; # git
      bg3 = hexcodes.red;
      fg4 = hexcodes.white; # lang/env
      bg4 = hexcodes.bright_magenta;
      fg5 = hexcodes.cyan; # time
      bg5 = hexcodes.magenta;
      bgchar = hexcodes.black;
    };
    ghostty = {
      palette0 = black;
      palette1 = red;
      palette2 = green;
      palette3 = yellow;
      palette4 = blue;
      palette5 = magenta;
      palette6 = cyan;
      palette7 = white;
      palette8 = bright_black;
      palette9 = bright_red;
      paletteA = bright_green;
      paletteB = bright_yellow;
      paletteC = bright_blue;
      paletteD = bright_magenta;
      paletteE = bright_cyan;
      paletteF = bright_white;
      cursor = bright_red;
    };
  };
  light = rec {
    name = "${theme_name}_light";
    author = "${theme_author}";
    is_light = true;
    base16 = {
      bg = fg;
      fg = bg;
      black = black;
      red = red;
      green = green;
      yellow = yellow;
      blue = blue;
      magenta = magenta;
      cyan = cyan;
      white = white;
      bright_black = bright_black;
      bright_red = bright_red;
      bright_green = bright_green;
      bright_yellow = bright_yellow;
      bright_blue = bright_blue;
      bright_magenta = bright_magenta;
      bright_cyan = bright_cyan;
      bright_white = bright_white;
      base00 = base16.bg;
      base01 = base16.blue;
      base02 = base16.bright_green;
      base03 = base16.yellow;
      base04 = base16.green;
      base05 = base16.fg;
      base06 = base16.bright_cyan;
      base07 = base16.bright_white;
      base08 = base16.cyan; # incomplete
      base09 = base16.magenta;
      base0A = base16.bright_white;
      base0B = base16.bright_yellow;
      base0C = base16.white;
      base0D = base16.bright_magenta;
      base0E = base16.bright_red;
      base0F = base16.red;
    };
    hexcodes = {
      bg = "#" + base16.bg;
      fg = "#" + base16.fg;
      black = "#" + base16.black;
      red = "#" + base16.red;
      green = "#" + base16.green;
      yellow = "#" + base16.yellow;
      blue = "#" + base16.blue;
      magenta = "#" + base16.magenta;
      cyan = "#" + base16.cyan;
      white = "#" + base16.white;
      bright_black = "#" + base16.bright_black;
      bright_red = "#" + base16.bright_red;
      bright_green = "#" + base16.bright_green;
      bright_yellow = "#" + base16.bright_yellow;
      bright_blue = "#" + base16.bright_blue;
      bright_magenta = "#" + base16.bright_magenta;
      bright_cyan = "#" + base16.bright_cyan;
      bright_white = "#" + base16.bright_white;
      window_focus = hexcodes.bright_red;
    };
    starship = {
      fg1 = hexcodes.yellow; # os
      bg1 = hexcodes.bright_green;
      fg2 = hexcodes.bright_cyan; # directory
      bg2 = hexcodes.bright_magenta;
      fg3 = hexcodes.red; # git
      bg3 = hexcodes.white;
      fg4 = hexcodes.black; # lang/env
      bg4 = hexcodes.bright_yellow;
      fg5 = hexcodes.blue; # time
      bg5 = hexcodes.bright_blue;
      bgchar = hexcodes.magenta;
    };
    ghostty = {
      palette0 = black;
      palette1 = red;
      palette2 = green;
      palette3 = yellow;
      palette4 = blue;
      palette5 = magenta;
      palette6 = cyan;
      palette7 = white;
      palette8 = bright_black;
      palette9 = bright_red;
      paletteA = bright_green;
      paletteB = bright_yellow;
      paletteC = bright_blue;
      paletteD = bright_magenta;
      paletteE = bright_cyan;
      paletteF = bright_white;
      cursor = red;
    };
  };
}
