require("handdara.config.telescope")
require("handdara.config.treesitter")
require("handdara.config.set")
require("handdara.config.snippet")
require("handdara.config.lsp")
require("handdara.config.keymap")
require("handdara.config.looks")
require("handdara.config.minifiles")
require("handdara.config.telekasten")
require("handdara.config.oil")
-- require("handdara.config.mkdnflow")
