set fallback

target := 'main'

jd := justfile_directory()
tmp_dir := `mktemp -d`
wezterm_cfg_dir := env_var('HOME') / '.config' / 'wezterm'

# just list cmds
default: 
    @just --list

# unlink main wezterm configuration symlink
unlink:
    -rm -f {{wezterm_cfg_dir}}

# purge main wezterm configuration directory recursively
purge: unlink
    rm -rf {{wezterm_cfg_dir}}

_link ltgt:
    ln -sv {{jd}}/wezterm-{{ltgt}} {{wezterm_cfg_dir}}

# symlink nvim configuration
link: (_link target)

# replace nix loaded config with symlink to nvim-main here
replace-nix: purge && link # the && here runs the subsequent recipes after this one
