wez_config_ln := env_var('HOME') / '.config' / 'wezterm'
wez_main_dir := justfile_directory() / 'wezterm-main'

# just list cmds
default: 
    @just --list

# symlink main wezterm configuration
link:
    rm -Rf {{wez_config_ln}}
    ln -sv {{wez_main_dir}} {{wez_config_ln}}

# unlink main wezterm configuration symlink
unlink:
    rm -f {{wez_config_ln}}

# purge main wezterm configuration directory recursively
purge: unlink
    rm -rf {{wez_config_ln}}

